### ISSUE TITLE
[Insight] Website should be protected against XSSVulnerability - in src/…/Partials/rawDescription.html.twig, line 2

### ISSUE THREAD

**Issue by morozovalexander** [morozovalexander/symfocommerce#12]
**[in src/Eshop/ShopBundle/Resources/views/Partials/rawDescription.html.twig, line 2](https://github.com/morozovalexander/symfocommerce/blob/e413849c544b4972c95fff5529641f6d25e557e3/src/Eshop/ShopBundle/Resources/views/Partials/rawDescription.html.twig#L2)**

> Using the `|raw` filter or the `{% autoescape false %}` block in a Twig template exposes users to Cross-Site Scripting (XSS) attacks

```jinja
{% autoescape 'html' %}
    {{ descr|raw|nl2br }}
{% endautoescape %}

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c3ca849d-a45a-43a9-b346-5422034fcc49/analyses/29?status=ignored)_

**Comment by yanntoque** [comment]
Thanks worked w/ Symfony 3.2.1

**Comment by morozovalexander** [comment]
@yanntoque Glad to help you!
